"""
email.py — Send HTML email via Gmail SMTP (TLS).

Falls back to plain-text if HTML is not supported.
To use Gmail:
  1. Enable 2-Factor Authentication on your Google account.
  2. Create an App Password at https://myaccount.google.com/apppasswords
  3. Set SMTP_USER and SMTP_PASSWORD in your .env file.
"""
import os
import asyncio
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv

load_dotenv()

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.environ["SMTP_USER"]
SMTP_PASSWORD = os.environ["SMTP_PASSWORD"]
FROM_NAME = os.getenv("FROM_NAME", "Rabbitt AI Sales Insights")


def _build_html_body(markdown_text: str) -> str:
    """Wrap the markdown summary in a minimal but professional HTML email template."""
    # Convert basic markdown to HTML (bold, bullets, headings)
    import re

    html = markdown_text
    # Headers
    html = re.sub(r"(?m)^## (.+)$", r"<h2>\1</h2>", html)
    html = re.sub(r"(?m)^# (.+)$", r"<h1>\1</h1>", html)
    # Bold
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    # Bullets
    html = re.sub(r"(?m)^- (.+)$", r"<li>\1</li>", html)
    html = re.sub(r"(<li>.*</li>)+", r"<ul>\g<0></ul>", html, flags=re.DOTALL)
    # Paragraphs
    html = re.sub(r"(?m)^(?!<[hlu])(.+)$", r"<p>\1</p>", html)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f5f7fa; margin: 0; padding: 0; }}
    .container {{ max-width: 680px; margin: 40px auto; background: #ffffff;
                  border-radius: 12px; overflow: hidden;
                  box-shadow: 0 4px 24px rgba(0,0,0,0.08); }}
    .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
               padding: 36px 40px; }}
    .header h1 {{ color: #ffffff; margin: 0; font-size: 22px; font-weight: 700; }}
    .header p {{ color: #a0aec0; margin: 6px 0 0; font-size: 13px; }}
    .body {{ padding: 40px; color: #2d3748; line-height: 1.7; }}
    h1,h2 {{ color: #1a202c; }}
    h2 {{ border-left: 4px solid #e53e3e; padding-left: 12px; margin-top: 28px; }}
    ul {{ padding-left: 20px; }}
    li {{ margin-bottom: 6px; }}
    .footer {{ background: #f7fafc; padding: 20px 40px;
               font-size: 12px; color: #718096; border-top: 1px solid #e2e8f0; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 Sales Insight Report</h1>
      <p>AI-generated by Rabbitt AI Sales Insight Automator</p>
    </div>
    <div class="body">
      {html}
    </div>
    <div class="footer">
      This report was auto-generated. Please do not reply to this email.
    </div>
  </div>
</body>
</html>"""


def _send_sync(recipient: str, subject: str, body: str) -> None:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{FROM_NAME} <{SMTP_USER}>"
    msg["To"] = recipient

    plain = MIMEText(body, "plain")
    html = MIMEText(_build_html_body(body), "html")
    msg.attach(plain)
    msg.attach(html)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_USER, recipient, msg.as_string())


async def send_email(recipient: str, subject: str, body: str) -> None:
    """Non-blocking wrapper — runs SMTP in a thread pool executor."""
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, _send_sync, recipient, subject, body)
